/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as LabRouteImport } from './routes/lab'
import { Route as ParalegalRouteImport } from './routes/paralegal'
import { Route as ReportRouteImport } from './routes/report'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as KnowledgeSlugRouteImport } from './routes/knowledge.$slug'
import { Route as ParalegalIndexRouteImport } from './routes/paralegal.index'
import { Route as ParalegalCaseIdRouteImport } from './routes/paralegal.$caseId'
import { Route as ParalegalCasesRouteImport } from './routes/paralegal.cases'
import { Route as ParalegalTrainingRouteImport } from './routes/paralegal.training'
import { Route as ParalegalLoginRouteImport } from './routes/paralegal_.login'
import { Route as ParalegalTrainingScenarioIdRouteImport } from './routes/paralegal.training.$scenarioId'
import { Route as ParalegalTrainingHistoryRouteImport } from './routes/paralegal.training.history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ParalegalRoute = ParalegalRouteImport.update({
  id: '/paralegal',
  path: '/paralegal',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeSlugRoute = KnowledgeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KnowledgeRoute,
} as any)
const ParalegalIndexRoute = ParalegalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParalegalRoute,
} as any)
const ParalegalCaseIdRoute = ParalegalCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => ParalegalRoute,
} as any)
const ParalegalCasesRoute = ParalegalCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => ParalegalRoute,
} as any)
const ParalegalTrainingRoute = ParalegalTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => ParalegalRoute,
} as any)
const ParalegalLoginRoute = ParalegalLoginRouteImport.update({
  id: '/paralegal_/login',
  path: '/paralegal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ParalegalTrainingScenarioIdRoute =
  ParalegalTrainingScenarioIdRouteImport.update({
    id: '/$scenarioId',
    path: '/$scenarioId',
    getParentRoute: () => ParalegalTrainingRoute,
  } as any)
const ParalegalTrainingHistoryRoute =
  ParalegalTrainingHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => ParalegalTrainingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/intake': typeof IntakeRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/lab': typeof LabRoute
  '/paralegal': typeof ParalegalRouteWithChildren
  '/report': typeof ReportRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/paralegal/$caseId': typeof ParalegalCaseIdRoute
  '/paralegal/cases': typeof ParalegalCasesRoute
  '/paralegal/training': typeof ParalegalTrainingRouteWithChildren
  '/paralegal/login': typeof ParalegalLoginRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/paralegal/': typeof ParalegalIndexRoute
  '/paralegal/training/$scenarioId': typeof ParalegalTrainingScenarioIdRoute
  '/paralegal/training/history': typeof ParalegalTrainingHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/intake': typeof IntakeRoute
  '/lab': typeof LabRoute
  '/report': typeof ReportRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/paralegal/$caseId': typeof ParalegalCaseIdRoute
  '/paralegal/cases': typeof ParalegalCasesRoute
  '/paralegal/training': typeof ParalegalTrainingRouteWithChildren
  '/paralegal/login': typeof ParalegalLoginRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/paralegal': typeof ParalegalIndexRoute
  '/paralegal/training/$scenarioId': typeof ParalegalTrainingScenarioIdRoute
  '/paralegal/training/history': typeof ParalegalTrainingHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/intake': typeof IntakeRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/lab': typeof LabRoute
  '/paralegal': typeof ParalegalRouteWithChildren
  '/report': typeof ReportRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/paralegal/$caseId': typeof ParalegalCaseIdRoute
  '/paralegal/cases': typeof ParalegalCasesRoute
  '/paralegal/training': typeof ParalegalTrainingRouteWithChildren
  '/paralegal_/login': typeof ParalegalLoginRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/paralegal/': typeof ParalegalIndexRoute
  '/paralegal/training/$scenarioId': typeof ParalegalTrainingScenarioIdRoute
  '/paralegal/training/history': typeof ParalegalTrainingHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/intake'
    | '/knowledge'
    | '/lab'
    | '/paralegal'
    | '/report'
    | '/knowledge/$slug'
    | '/paralegal/$caseId'
    | '/paralegal/cases'
    | '/paralegal/training'
    | '/paralegal/login'
    | '/knowledge/'
    | '/paralegal/'
    | '/paralegal/training/$scenarioId'
    | '/paralegal/training/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/intake'
    | '/lab'
    | '/report'
    | '/knowledge/$slug'
    | '/paralegal/$caseId'
    | '/paralegal/cases'
    | '/paralegal/training'
    | '/paralegal/login'
    | '/knowledge'
    | '/paralegal'
    | '/paralegal/training/$scenarioId'
    | '/paralegal/training/history'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/intake'
    | '/knowledge'
    | '/lab'
    | '/paralegal'
    | '/report'
    | '/knowledge/$slug'
    | '/paralegal/$caseId'
    | '/paralegal/cases'
    | '/paralegal/training'
    | '/paralegal_/login'
    | '/knowledge/'
    | '/paralegal/'
    | '/paralegal/training/$scenarioId'
    | '/paralegal/training/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  IntakeRoute: typeof IntakeRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  LabRoute: typeof LabRoute
  ParalegalRoute: typeof ParalegalRouteWithChildren
  ReportRoute: typeof ReportRoute
  ParalegalLoginRoute: typeof ParalegalLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paralegal': {
      id: '/paralegal'
      path: '/paralegal'
      fullPath: '/paralegal'
      preLoaderRoute: typeof ParalegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/$slug': {
      id: '/knowledge/$slug'
      path: '/$slug'
      fullPath: '/knowledge/$slug'
      preLoaderRoute: typeof KnowledgeSlugRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/paralegal/': {
      id: '/paralegal/'
      path: '/'
      fullPath: '/paralegal/'
      preLoaderRoute: typeof ParalegalIndexRouteImport
      parentRoute: typeof ParalegalRoute
    }
    '/paralegal/$caseId': {
      id: '/paralegal/$caseId'
      path: '/$caseId'
      fullPath: '/paralegal/$caseId'
      preLoaderRoute: typeof ParalegalCaseIdRouteImport
      parentRoute: typeof ParalegalRoute
    }
    '/paralegal/cases': {
      id: '/paralegal/cases'
      path: '/cases'
      fullPath: '/paralegal/cases'
      preLoaderRoute: typeof ParalegalCasesRouteImport
      parentRoute: typeof ParalegalRoute
    }
    '/paralegal/training': {
      id: '/paralegal/training'
      path: '/training'
      fullPath: '/paralegal/training'
      preLoaderRoute: typeof ParalegalTrainingRouteImport
      parentRoute: typeof ParalegalRoute
    }
    '/paralegal_/login': {
      id: '/paralegal_/login'
      path: '/paralegal/login'
      fullPath: '/paralegal/login'
      preLoaderRoute: typeof ParalegalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paralegal/training/$scenarioId': {
      id: '/paralegal/training/$scenarioId'
      path: '/$scenarioId'
      fullPath: '/paralegal/training/$scenarioId'
      preLoaderRoute: typeof ParalegalTrainingScenarioIdRouteImport
      parentRoute: typeof ParalegalTrainingRoute
    }
    '/paralegal/training/history': {
      id: '/paralegal/training/history'
      path: '/history'
      fullPath: '/paralegal/training/history'
      preLoaderRoute: typeof ParalegalTrainingHistoryRouteImport
      parentRoute: typeof ParalegalTrainingRoute
    }
  }
}

interface KnowledgeRouteChildren {
  KnowledgeSlugRoute: typeof KnowledgeSlugRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeSlugRoute: KnowledgeSlugRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface ParalegalTrainingRouteChildren {
  ParalegalTrainingScenarioIdRoute: typeof ParalegalTrainingScenarioIdRoute
  ParalegalTrainingHistoryRoute: typeof ParalegalTrainingHistoryRoute
}

const ParalegalTrainingRouteChildren: ParalegalTrainingRouteChildren = {
  ParalegalTrainingScenarioIdRoute: ParalegalTrainingScenarioIdRoute,
  ParalegalTrainingHistoryRoute: ParalegalTrainingHistoryRoute,
}

const ParalegalTrainingRouteWithChildren =
  ParalegalTrainingRoute._addFileChildren(ParalegalTrainingRouteChildren)

interface ParalegalRouteChildren {
  ParalegalCaseIdRoute: typeof ParalegalCaseIdRoute
  ParalegalCasesRoute: typeof ParalegalCasesRoute
  ParalegalTrainingRoute: typeof ParalegalTrainingRouteWithChildren
  ParalegalIndexRoute: typeof ParalegalIndexRoute
}

const ParalegalRouteChildren: ParalegalRouteChildren = {
  ParalegalCaseIdRoute: ParalegalCaseIdRoute,
  ParalegalCasesRoute: ParalegalCasesRoute,
  ParalegalTrainingRoute: ParalegalTrainingRouteWithChildren,
  ParalegalIndexRoute: ParalegalIndexRoute,
}

const ParalegalRouteWithChildren = ParalegalRoute._addFileChildren(
  ParalegalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  IntakeRoute: IntakeRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  LabRoute: LabRoute,
  ParalegalRoute: ParalegalRouteWithChildren,
  ReportRoute: ReportRoute,
  ParalegalLoginRoute: ParalegalLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
